[package]
name = "rust_examples"
version = "0.1.1"
edition = "2021"

[dependencies]
roqoqo = {version="1.0.0-alpha.5"}
roqoqo-quest = {version="0.7"}
num-complex = "0.4"
qoqo_calculator = "0.8.3"
ndarray = { version = "0.15" }
eigenvalues = "0.4"
nalgebra = "0.30"
serde_json = "1.0"
